title: Emile Lampe # your name (or website title) here
logo: "/images/portfolio_image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc Computer Science student at TU Delft, specializing in Artificial Intelligence. Work experience in automation. Driven by curiosity and innovation, I am dedicated to developing impactful AI solutions.
  <br><br>
  In my spare time, I enjoy exploring creative projects and challenging myself in endurance sports.
  <br><br>
  <a href="https://www.linkedin.com/in/emile-lampe-5825b057/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-D0G05WPTJM # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
